name: New Feature
description: Request a new feature to be added to deb-get.
title: "Feature Request: "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
      ## Requesting a new feature 🧑‍💻
      Please describe the proposed feature with as much detail as possible:
- type: textarea
  id: new-feature
  attributes:
    label: New Feature
    render: markdown
  validations:
    required: true
